### ISSUE TITLE
Current_Temperature not changing

### ISSUE THREAD

**Issue by FSFirenze** [grivkees/homebridge-carrier-infinity#462]
I am playing with this integration for HomeBridge, and using it to read & control the Carrier Infinity system from HomeAssistant (I am not looking at HomeKit right now). Everything runs on a Raspberry PI4 with Docker on it.

**Question 1**
I am noticing that the value i receive for the measured temperature is practically constant and very often identical to the Cooling To: temperature, see the below where Current Temperature = Cooling Threshold Temperature. Moreover, that temperature has been exactly 75.92degF for 12 hours now.
This seems a bit odd to say the least, is there another variable I should look at that provides a more realistic temperature?

Current Temperature	75.92°
Target Temperature	71.96000000000001°
Cooling Threshold Temperature	75.92°
Heating Threshold Temperature	68°
Current Relative Humidity	50%
Manufacturer	Carrier Home
Model	SYSTXCCITC01-B
Firmware Revision	1.6.7

**Question 2**
What is the "Target Temperature" reading? My thermostat is currently set in heat/cool mode, keeping the range 68-76 degF

Thank you!

**Comment by grivkees** [comment]
Hey!

So in HomeKit all temperatures are stored internally in Celsius. So this is really saying 76 degrees, not 75.92. The oddly specific number here is just an artifact of HomeKit storing the temp in C imprecisely and converting it to F before it shows it to you. If you were looking at this in HomeKit itself, it would round it to 76 before showing it to you.

Because of this, and the fact that HK and your thermostat still only store F temps to the nearest degree, the only way you will see this value change will be if the F temp goes up a full degree to 77 or down to 75. If that happens you will then see a different, but still oddly specific value. Because your system is correctly keeping your house cooled to 76 degrees, it is expected that your cool point and your current temp should stay the same. (If you manually raise or lower your cool setpoint past the current temp, you should see them diverge until your house reaches that point again)

As for what is 'Target Temp' when your system is in head/cool mode: it is just an average of heat and cool points. Its not actually used anywhere by homekit when your system is in auto heat/cool mode. But it needs to be set to something. If you change your system to heat or cool only mode, HomeKit then ignores the 'threshold' temps and begins using this 'Target Temp' setting, at which point Target Temp will be changed to match the heat set point (for head mode) or cool setpoint (for cool mode).
