### ISSUE TITLE
Fan Speed Issue

### ISSUE THREAD

**Issue by R1Lover** [grivkees/homebridge-carrier-infinity#85]
Fan speed currently shows a setting of off, 33%, 66% and 100%, there should also be an "auto" mode available.

**Comment by grivkees** [comment]
Hey @R1Lover! There's an explanation here: https://github.com/grivkees/homebridge-carrier-infinity/wiki/Configuration#controls

tl;dr if your system is on, setting fan=0 is actually setting fan=auto. Think of it as the fan override being off, not the fan itself being off.

There's unfortunately no good way to show 'auto' in homekit right now. And since you can't actually even turn off the fan when the system is on, using off for auto seemed like the best way to go.

Open to other suggestions on this, though.

**Comment by grivkees** [comment]
Clarified the wiki a bit more. https://github.com/grivkees/homebridge-carrier-infinity/wiki/Configuration#controls

If you have any other suggestions on how to make this clearer, let me know and feel free to reopen.

**Comment by R1Lover** [comment]
Thanks for the clarification and update to the wiki. perhaps the only suggestion I can recommend is changing the "off" to "auto" or "off/auto" Appreciate your work on this and the information you provided. :)

**Comment by grivkees** [comment]
With the most recent update (1.5.0, available as homebridge-carrier-infinity@next), under the fan slider there is an unlabeled blue circle that represents auto/manual. This is unfortunately how homekit chooses to show the setting.

I did figure out a way to make homekit show a separate a manual/auto button too. First, you need to split the thermostat/fan into separate tiles. In homekit, under the settings or this accessory, click "show as separate tiles". Then, under the new separate fan accessory, scroll down or click the settings gear, and you should see a new setting item labeled "fan mode" which slides between auto and manual.
