### ISSUE TITLE
Outdoor temperature shows in degrees F even with C selected

### ISSUE THREAD

**Issue by Aqualung812** [grivkees/homebridge-carrier-infinity#97]
**Describe The Bug:**
When the outdoor unit temperature sensor is enabled in HomeKit, and the iOS device is set to use Celsius, the temp is still shown in degrees F, but without a label, making the temperature look much warmer than it is.  

**To Reproduce:**
Enable outdoor temperature sensor in HomeBridge
Set iOS device to use degrees Celsius
View outdoor temperature sensor and compare to actual temperature. 

**Expected behavior:**
Outdoor temperature sensor should display degrees that match the iOS setting.

**Logs:**

N/A

**Plugin Config:**

    "username": ----
    "password": ----
    "holdBehavior": "activity",
    "showOutdoorTemperatureSensor": true,
    "showFanControl": true,
    "showIndoorHumiditySensors": false,
    "_bridge": {
        "username": "-----",
        "port": 59180
    },
    "platform": "CarrierInfinity"
}

**Screenshots:**

The "sides" room is the temp sensor for the outdoor unit. Compare to the weather station in the back yard at 20.5C, outdoor unit shows 67C. 

![image](https://user-images.githubusercontent.com/90048888/132016282-5b89da5d-955d-4c3d-92d4-ea2cd2218328.png)

**Environment:**

* homebridge-carrier-infinity v1.4.0:
* **Homebridge Version**: v1.3.4
* **Node.js Version**: v14.15.0
* **NPM Version**: v6.14.8
* **Operating System**: Raspbian

**Comment by EHylands** [comment]
I was about to report the same behavior on my system using celsius. 

The plugin is using the same functions to report and convert zones and outside temperature. Is Carrier API reporting the wrong units for  the outside temperature ?

class OATSensorTemp extends CharacteristicWrapper {
  ctype = this.Characteristic.CurrentTemperature;
  get = async () => {
    return convertSystemTemp2CharTemp(
      await this.system.status.getOutdoorTemp(),
      await this.system.status.getUnits(),
    );
  };
}

**Comment by Aqualung812** [comment]
If it is helpful, it appears that in my Homebridge, I'm stilling running F and it shows an incorrect temp there as well. 
![image](https://user-images.githubusercontent.com/90048888/132353703-81d8749d-d7da-4a7f-86fe-67a02560a0ff.png)

**Comment by grivkees** [comment]
Thanks for the report @Aqualung812 !

HomeKit actually stores everything in Celsius, so the plugin converts from whatever the Carrier API reports to C, and then if your HomeKit is set to F, HomeKit converts it back...

@EHylands I think you are right. My best guess here is that your AC system itself is set to celsius, so the set points and everything reported by carrier are C, but for some reason the carrier api still reports the outdoor temp as F, so we end up double converting it since I assumed the outdoor sensor would use the same units as the system.

Can one of you take a look at the instructions here, and send me your system's 'status' response: https://github.com/grivkees/homebridge-carrier-infinity/wiki/Development#investigating-carrier-api-responses

Once I get that and can confirm this is actually the issue, I can put up a fix.

**Comment by EHylands** [comment]
Outside temperature is effectively reported as 54 celsius degrees on carrier web site. Unit on the api are wrong. working to provide requested files.

**Comment by EHylands** [comment]
</name><oat>54</oat><mode>off</mode><cfgem>C</cfgem>

**Comment by grivkees** [comment]
@EHylands Perfect!

And just to confirm, its not actually 54 C outside? Its 12 C outside?

**Comment by EHylands** [comment]
It is actually 12C right now so 54F.Thank you for your time !

**Comment by Aqualung812** [comment]
Confirmed, resolved in my instance as well, thanks!
